### ISSUE TITLE
Front-end build issue

### ISSUE THREAD

**Issue by MohammadPCh** [Giveth/giveth-dapps-v2#2701]
When I'm trying to build our project on my machine  get this error:
```
[GraphQL error]: remaining connection slots are reserved for non-replication superuser connections { locations: [ { line: 93, column: 3 } ], path: [ 'projectUpdates' ] }
[GraphQL error]: remaining connection slots are reserved for non-replication superuser connections {
  locations: [ { line: 80, column: 3 } ],
  path: [ 'donationsTotalUsdPerDate' ]
}
[GraphQL error]: remaining connection slots are reserved for non-replication superuser connections { locations: [ { line: 116, column: 3 } ], path: [ 'campaigns' ] }
[GraphQL error]: remaining connection slots are reserved for non-replication superuser connections {
  locations: [ { line: 83, column: 3 } ],
  path: [ 'featuredProjects' ]
}

Error occurred prerendering page "/ca". Read more: https://nextjs.org/docs/messages/prerender-error
ApolloError: remaining connection slots are reserved for non-replication superuser connections
remaining connection slots are reserved for non-replication superuser connections
remaining connection slots are reserved for non-replication superuser connections
remaining connection slots are reserved for non-replication superuser connections
    at new ApolloError (/home/lobater/projects/giveth-dapps-v2/node_modules/@apollo/client/errors/errors.cjs:34:28)
    at /home/lobater/projects/giveth-dapps-v2/node_modules/@apollo/client/core/core.cjs:1833:47
    at both (/home/lobater/projects/giveth-dapps-v2/node_modules/@apollo/client/utilities/utilities.cjs:1068:53)
    at /home/lobater/projects/giveth-dapps-v2/node_modules/@apollo/client/utilities/utilities.cjs:1061:72
    at new Promise (<anonymous>)
    at Object.then (/home/lobater/projects/giveth-dapps-v2/node_modules/@apollo/client/utilities/utilities.cjs:1061:24)
    at Object.next (/home/lobater/projects/giveth-dapps-v2/node_modules/@apollo/client/utilities/utilities.cjs:1069:49)
    at notifySubscription (/home/lobater/projects/giveth-dapps-v2/node_modules/zen-observable/lib/Observable.js:135:18)
    at onNotify (/home/lobater/projects/giveth-dapps-v2/node_modules/zen-observable/lib/Observable.js:179:3)
    at SubscriptionObserver.next (/home/lobater/projects/giveth-dapps-v2/node_modules/zen-observable/lib/Observable.js:235:7)
[    ] info  - Generating static pages (137/142)[GraphQL error]: remaining connection slots are reserved for non-replication superuser connections {
  locations: [ { line: 62, column: 3 } ],
  path: [ 'findCampaignBySlug' ]
}
[GraphQL error]: remaining connection slots are reserved for non-replication superuser connections {
  locations: [ { line: 62, column: 3 } ],
  path: [ 'findCampaignBySlug' ]
}
[ ===] info  - Generating static pages (140/142)[GraphQL error]: remaining connection slots are reserved for non-replication superuser connections { locations: [ { line: 116, column: 3 } ], path: [ 'campaigns' ] }

Error occurred prerendering page "/es". Read more: https://nextjs.org/docs/messages/prerender-error
ApolloError: remaining connection slots are reserved for non-replication superuser connections
    at new ApolloError (/home/lobater/projects/giveth-dapps-v2/node_modules/@apollo/client/errors/errors.cjs:34:28)
    at /home/lobater/projects/giveth-dapps-v2/node_modules/@apollo/client/core/core.cjs:1833:47
    at both (/home/lobater/projects/giveth-dapps-v2/node_modules/@apollo/client/utilities/utilities.cjs:1068:53)
    at /home/lobater/projects/giveth-dapps-v2/node_modules/@apollo/client/utilities/utilities.cjs:1061:72
    at new Promise (<anonymous>)
    at Object.then (/home/lobater/projects/giveth-dapps-v2/node_modules/@apollo/client/utilities/utilities.cjs:1061:24)
    at Object.next (/home/lobater/projects/giveth-dapps-v2/node_modules/@apollo/client/utilities/utilities.cjs:1069:49)
    at notifySubscription (/home/lobater/projects/giveth-dapps-v2/node_modules/zen-observable/lib/Observable.js:135:18)
    at onNotify (/home/lobater/projects/giveth-dapps-v2/node_modules/zen-observable/lib/Observable.js:179:3)
    at SubscriptionObserver.next (/home/lobater/projects/giveth-dapps-v2/node_modules/zen-observable/lib/Observable.js:235:7)
info  - Generating static pages (142/142)

> Build error occurred
Error: Export encountered errors on following paths:
	/: /ca
	/: /es
    at /home/lobater/projects/giveth-dapps-v2/node_modules/next/dist/export/index.js:415:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Span.traceAsyncFn (/home/lobater/projects/giveth-dapps-v2/node_modules/next/dist/trace/trace.js:79:20)
    at async /home/lobater/projects/giveth-dapps-v2/node_modules/next/dist/build/index.js:1400:21
    at async Span.traceAsyncFn (/home/lobater/projects/giveth-dapps-v2/node_modules/next/dist/trace/trace.js:79:20)
    at async /home/lobater/projects/giveth-dapps-v2/node_modules/next/dist/build/index.js:1259:17
    at async Span.traceAsyncFn (/home/lobater/projects/giveth-dapps-v2/node_modules/next/dist/trace/trace.js:79:20)
    at async Object.build [as default] (/home/lobater/projects/giveth-dapps-v2/node_modules/next/dist/build/index.js:66:29)
error Command failed with exit code 1.
```
Besides that, we have this error on the Vercel. It's a really serious problem because we need to release a hot fix:
https://vercel.com/givethio/giveth-dapps-v2/7z6xsF6tfd8cJLjeLKm9ZbgNC8KN
![image](https://github.com/Giveth/giveth-dapps-v2/assets/17097576/d0078543-9b24-4a12-a336-48bcacbfdb88)
@aminlatifi can you take a look?

**Comment by MohammadPCh** [comment]
We have this problem in both the staging and production environments.
as I know this is a Postgres Error message.
All of our builds even in GitHub failed.
