### ISSUE TITLE
CAN'T DONATE IN NATIVE TOKENS - call revert exception

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#352]
testing on `staging.giveth.io` on firefox and brave

When I try to donate on either ropsten or xdai I am unable to donate in ETH or xDAI respectively. I receive a lengthy `call revert exception` error. 

![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/77404a02-ab58-4c29-9a11-d73b4834b119)

I tested a few ERC-20 tokens and there seems to be no issue 

Here is the output of the error from the console: 
```
Error sending transaction:  Objecterror: Error: call revert exception (method="decimals()", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.5.0)
    at d.makeError (https://staging.giveth.io/_next/static/chunks/pages/_app-71424d3636073c20.js:1:81478)
    at d.throwError (https://staging.giveth.io/_next/static/chunks/pages/_app-71424d3636073c20.js:1:81598)
    at w.decodeFunctionResult (https://staging.giveth.io/_next/static/chunks/pages/_app-71424d3636073c20.js:1:29997)
    at https://staging.giveth.io/_next/static/chunks/pages/_app-71424d3636073c20.js:1:60139
    at Generator.next (<anonymous>)
    at a (https://staging.giveth.io/_next/static/chunks/pages/_app-71424d3636073c20.js:1:55949)address: "0x0000000000000000000000000000000000000000"args: Array(0)length: 0[[Prototype]]: Array(0)code: "CALL_EXCEPTION"errorArgs: nullerrorName: nullerrorSignature: nullmethod: "decimals()"reason: nulltransaction: data: "0x313ce567"to: "0x0000000000000000000000000000000000000000"[[Prototype]]: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()__proto__: (...)get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()message: "call revert exception (method=\"decimals()\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.5.0)"stack: "Error: call revert exception (method=\"decimals()\", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.5.0)\n    at d.makeError (https://staging.giveth.io/_next/static/chunks/pages/_app-71424d3636073c20.js:1:81478)\n    at d.throwError (https://staging.giveth.io/_next/static/chunks/pages/_app-71424d3636073c20.js:1:81598)\n    at w.decodeFunctionResult (https://staging.giveth.io/_next/static/chunks/pages/_app-71424d3636073c20.js:1:29997)\n    at https://staging.giveth.io/_next/static/chunks/pages/_app-71424d3636073c20.js:1:60139\n    at Generator.next (<anonymous>)\n    at a (https://staging.giveth.io/_next/static/chunks/pages/_app-71424d3636073c20.js:1:55949)"__sentry_captured__: true[[Prototype]]: Objectconstructor: ƒ Error()message: ""name: "Error"toString: ƒ toString()[[Prototype]]: Object[[Prototype]]: Object
1921-8c88fe2bb03adee7.js:1 Error: call revert exception (method="decimals()", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.5.0)
    at d.makeError (_app-71424d3636073c20.js:1:81478)
    at d.throwError (_app-71424d3636073c20.js:1:81598)
    at w.decodeFunctionResult (_app-71424d3636073c20.js:1:29997)
    at _app-71424d3636073c20.js:1:60139
    at Generator.next (<anonymous>)
    at a (_app-71424d3636073c20.js:1:55949)
```

**Comment by divine-comedian** [comment]
tested on `staging.giveth.io` 

successfully created tx to donate xDai on GC or ETH on ropsten! 

I also was able to create the donate tx on mainnet with ETH on `giveth.io` 

This issue looks to be resolved!
