### ISSUE TITLE
Set up new instance of GIVpower unlock bot to manage locked GIV on Polygon zkEVM

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4440]

**Comment by laurenluz** [comment]
@mhmdksh or @geleeroyale can you help with this? @aminlatifi says you know how to do it

**Comment by geleeroyale** [comment]
Hi Lauren - the givpower bot for Cardona is up and running. We only need to send some gas to the bot address.

**Comment by maryjaf** [comment]
- [ ] Is there a way to check the unlock scenario sooner than 3 Sep ? @aminlatifi @geleeroyale 

![image](https://github.com/user-attachments/assets/d68b9a0e-03de-48ea-b3ae-af5550f6ce72)

**Comment by aminlatifi** [comment]
N

**Comment by aminlatifi** [comment]
> - [ ] Is there a way to check the unlock scenario sooner than 3 Sep ? @aminlatifi @geleeroyale 
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/d68b9a0e-03de-48ea-b3ae-af5550f6ce72)
> 
> 

No! Contract doesn't allow us

**Comment by laurenluz** [comment]
I guess we can test it on prod if we push this change live by Sept 3.... and then just make sure that mary's tokens are unlock 🤔 

or is there a better way to ensure this doesn't have issues @aminlatifi @mohammadranjbarz ?

**Comment by geleeroyale** [comment]
givpower-bot is running for staging and production. The production wallet still needs to be funden with Polygon zkEVM gas: `0x4ddc12737b28b0413539c4b044f0c10abd85c07c`

**Comment by laurenluz** [comment]
@aminlatifi @mohammadranjbarz do you need me to coordinate getting some bot gas money from somewhere? or did you already have that sorted?

**Comment by mohammadranjbarz** [comment]
> @aminlatifi @mohammadranjbarz do you need me to coordinate getting some bot gas money from somewhere? or did you already have that sorted?

@geleeroyale has done it, need to wait for @maryjaf to confirms it at the end of the round

**Comment by laurenluz** [comment]
there is some problem with the unlock bot, it's not unlocking this... is it because it's missing gas?

**Comment by Rolazo** [comment]
Hey guys we're facing the following issues with the givepower bot for ZKEVM:

`[2024-09-03T18:44:17.434Z] error: Error on executing unlock transaction processing response error (body="{\"id\":52,\"jsonrpc\":\"2.0\",\"error\":{\"message\":\"RPC error response: invalid sender\",\"code\":-32000}}", error={"code":-32000}, requestBody="{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0x02f8f282044d808459682f008459682f00830160a994c790f82bf6f8709aa4a56dc11afad7af7c2a986780b884d034442c0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000003a0000000000000000000000000000000000000000000000000000000000000001000000000000000000000000d30e526d3b5a65c68c0224fdad1096c9023b4f1bc080a039c35aecb52781d594309422a3978acb3596b5e09f305df2703877ffe23a67a2a02981f9d044f5701ebf994524091aed5a4ea6cf6a14666d4bdc6fe6b6adbdfe00\"],\"id\":52,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://lb.drpc.org/ogrpc?network=polygon-zkevm&dkey=AkwVEpAy8kYom-mKjqkdWlUaFnt7WiIR75EnWq9OWu41", code=SERVER_ERROR, version=web/5.7.1) Error: processing response error (body="{\"id\":52,\"jsonrpc\":\"2.0\",\"error\":{\"message\":\"RPC error response: invalid sender\",\"code\":-32000}}", error={"code":-32000}, requestBody="{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0x02f8f282044d808459682f008459682f00830160a994c790f82bf6f8709aa4a56dc11afad7af7c2a986780b884d034442c0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000003a0000000000000000000000000000000000000000000000000000000000000001000000000000000000000000d30e526d3b5a65c68c0224fdad1096c9023b4f1bc080a039c35aecb52781d594309422a3978acb3596b5e09f305df2703877ffe23a67a2a02981f9d044f5701ebf994524091aed5a4ea6cf6a14666d4bdc6fe6b6adbdfe00\"],\"id\":52,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://lb.drpc.org/ogrpc?network=polygon-zkevm&dkey=AkwVEpAy8kYom-mKjqkdWlUaFnt7WiIR75EnWq9OWu41", code=SERVER_ERROR, version=web/5.7.1)
    at Logger.makeError (/usr/src/app/node_modules/@ethersproject/logger/lib/index.js:238:21)
    at Logger.throwError (/usr/src/app/node_modules/@ethersproject/logger/lib/index.js:247:20)
    at /usr/src/app/node_modules/@ethersproject/web/lib/index.js:313:32
    at step (/usr/src/app/node_modules/@ethersproject/web/lib/index.js:33:23)
    at Object.next (/usr/src/app/node_modules/@ethersproject/web/lib/index.js:14:53)
    at fulfilled (/usr/src/app/node_modules/@ethersproject/web/lib/index.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  reason: 'processing response error',
  code: 'SERVER_ERROR',
  body: '{"id":52,"jsonrpc":"2.0","error":{"message":"RPC error response: invalid sender","code":-32000}}',
  error: Error: RPC error response: invalid sender
      at getResult (/usr/src/app/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:191:21)
      at processJsonFunc (/usr/src/app/node_modules/@ethersproject/web/lib/index.js:356:22)
      at /usr/src/app/node_modules/@ethersproject/web/lib/index.js:288:46
      at step (/usr/src/app/node_modules/@ethersproject/web/lib/index.js:33:23)
      at Object.next (/usr/src/app/node_modules/@ethersproject/web/lib/index.js:14:53)
      at fulfilled (/usr/src/app/node_modules/@ethersproject/web/lib/index.js:5:58)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    code: -32000,
    data: undefined
  },
  requestBody: '{"method":"eth_sendRawTransaction","params":["0x02f8f282044d808459682f008459682f00830160a994c790f82bf6f8709aa4a56dc11afad7af7c2a986780b884d034442c0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000003a0000000000000000000000000000000000000000000000000000000000000001000000000000000000000000d30e526d3b5a65c68c0224fdad1096c9023b4f1bc080a039c35aecb52781d594309422a3978acb3596b5e09f305df2703877ffe23a67a2a02981f9d044f5701ebf994524091aed5a4ea6cf6a14666d4bdc6fe6b6adbdfe00"],"id":52,"jsonrpc":"2.0"}',
  requestMethod: 'POST',
  url: 'https://lb.drpc.org/ogrpc?network=polygon-zkevm&dkey=AkwVEpAy8kYom-mKjqkdWlUaFnt7WiIR75EnWq9OWu41',
  transaction: {
    type: 2,
    chainId: 1101,
    nonce: 0,
    maxPriorityFeePerGas: BigNumber { _hex: '0x59682f00', _isBigNumber: true },
    maxFeePerGas: BigNumber { _hex: '0x59682f00', _isBigNumber: true },
    gasPrice: null,
    gasLimit: BigNumber { _hex: '0x0160a9', _isBigNumber: true },
    to: '0xc790f82bF6F8709aa4A56dc11afaD7aF7C2a9867',
    value: BigNumber { _hex: '0x00', _isBigNumber: true },
    data: '0xd034442c0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000003a0000000000000000000000000000000000000000000000000000000000000001000000000000000000000000d30e526d3b5a65c68c0224fdad1096c9023b4f1b',
    accessList: [],
    hash: '0x63ff544a86f710550fd0eb6b0257f42bdc5872d1095bb911732010cbde78b513',
    v: 0,
    r: '0x39c35aecb52781d594309422a3978acb3596b5e09f305df2703877ffe23a67a2',
    s: '0x2981f9d044f5701ebf994524091aed5a4ea6cf6a14666d4bdc6fe6b6adbdfe00',
    from: '0x4DDC12737B28B0413539c4B044f0C10Abd85c07c',
    confirmations: 0
  },
  transactionHash: '0x63ff544a86f710550fd0eb6b0257f42bdc5872d1095bb911732010cbde78b513'
}`

**Comment by laurenluz** [comment]
@aminlatifi @geleeroyale can you help investigate what's happening when you're up? it's ok that this isn't working today... but we should solve it before the 1st live unlock in weeks... so would love to fix it this week if we can

**Comment by geleeroyale** [comment]
Thanks for supplying some gas @laurenluz - these errors started last night. I can also see them on RPC dashboard:

<img width="878" alt="image" src="https://github.com/user-attachments/assets/fc4f80b9-d877-479f-969d-9a18914a7d4c">

The key is not restricted in any way, so it might be an error with the application. Only the `eth_sendRawTransaction` calls get rejected by the RPC.

<img width="878" alt="image" src="https://github.com/user-attachments/assets/fa682cc0-dee2-46f5-b67f-48fbe4784eb1">

**Comment by geleeroyale** [comment]
@Rolazo Please be careful when posting raw logs - you exposed the API key with your message (the issue board for giveth-dapps-v2 is public)

**Comment by aminlatifi** [comment]
@geleeroyale I am suspicious about gas setting. Poloygon zkevm seems to have a different setting

**Comment by aminlatifi** [comment]
@geleeroyale I am making a PR, to don't override the gas setting optionally. Will let you know when it's finished.

**Comment by aminlatifi** [comment]
@geleeroyale The PR is merged, I tested on my machine and it worked!

Just set this in the env NO_GAS_OVERRIDE=true

**Comment by geleeroyale** [comment]
The failed requests for eth_sendRawTransaction are going down, but eth_estimateGas error rate is going up

<img width="900" alt="image" src="https://github.com/user-attachments/assets/c033a2d1-3fe9-428e-aebb-2d3285b22baf">

**Comment by maryjaf** [comment]
For this account **0xcd192b61a8Dd586A97592555c1f5709e032F2505** the locked GIV has been unlocked on zkEVM but my user hasn't received any notification related to unlock  @mohammadranjbarz

**Comment by mohammadranjbarz** [comment]
> For this account **0xcd192b61a8Dd586A97592555c1f5709e032F2505** the locked GIV has been unlocked on zkEVM but my user hasn't received any notification related to unlock @mohammadranjbarz

We didn't have `ZKEVM_PROVIDER` in the config of givEconomy-notificatio-service project, I just added it and restarted the application. @mhmdksh how can I see the logs for this application it's not in the grafana(or maybe I don't have access to that)

**Comment by mohammadranjbarz** [comment]
> > For this account **0xcd192b61a8Dd586A97592555c1f5709e032F2505** the locked GIV has been unlocked on zkEVM but my user hasn't received any notification related to unlock @mohammadranjbarz
> 
> We didn't have `ZKEVM_PROVIDER` in the config of givEconomy-notificatio-service project, I just added it and restarted the application. @mhmdksh how can I see the logs for this application it's not in the grafana(or maybe I don't have access to that)

@mhmdksh  @geleeroyale  Can you help me to see the logs, it would help me for investigating the problem

**Comment by mhmdksh** [comment]
> > > For this account **0xcd192b61a8Dd586A97592555c1f5709e032F2505** the locked GIV has been unlocked on zkEVM but my user hasn't received any notification related to unlock @mohammadranjbarz
> > 
> > 
> > We didn't have `ZKEVM_PROVIDER` in the config of givEconomy-notificatio-service project, I just added it and restarted the application. @mhmdksh how can I see the logs for this application it's not in the grafana(or maybe I don't have access to that)
> 
> @mhmdksh @geleeroyale Can you help me to see the logs, it would help me for investigating the problem

@geleeroyale Can you support with this?

**Comment by geleeroyale** [comment]
@mhmdksh Yes I did - but I did not update it in the issue here. I also invited you to drpc as I was the only one who had access.
